export const SET_BOOK = 'SET_BOOK';
export const GET_EDITED_BOOK = 'GET_EDITED_BOOK';
export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const ADD_BOOK= 'ADD_BOOKS_SUCCESS';
export const DELETE_BOOK= 'DELETE_BOOK_SUCCESS';
export const UPDATE_BOOK= 'UPDATE_BOOK_SUCCESS';